#!/bin/sh
# [Gedit Tool]
# Name=LaTeX -> PS
# Shortcut=<Primary>8
# Languages=latex
# Applicability=titled
# Output=output-panel
# Input=document
# Save-files=document


#!/bin/sh
filename=$GEDIT_CURRENT_DOCUMENT_NAME
basename=${filename%.*}

# Invoke rubber to parse TeX/LaTeX files as 
# many times as required to solve all references
rubber --inplace --maxerr -1 --short --force --warn all --ps "$filename"

# Open PDF output
xdg-open "$basename.ps" &

